POST http://localhost:3002/api/users 
content-type: application/json

{
  "username": "ubisecure",
  "password": "ubisecure",
  "firstname": "Teppo",
  "lastname": "Testaaja",
  "email": "testaaja@test.fi"
}